# Generated by Django 2.2.7 on 2019-11-09 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Ancestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('preposition', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True)),
                ('date_of_death', models.DateField(blank=True)),
                ('mothers_side', models.BooleanField(blank=True)),
                ('fathers_side', models.BooleanField(blank=True)),
                ('mutation_ts', models.DateTimeField(auto_now=True)),
                ('place_of_birth', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='place_of_birth', to='maps.City')),
                ('place_of_death', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='place_of_death', to='maps.City')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
