# Generated by Django 2.2.7 on 2019-11-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancestor',
            name='place_of_birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='place_of_birth', to='maps.City'),
        ),
        migrations.AlterField(
            model_name='ancestor',
            name='place_of_death',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='place_of_death', to='maps.City'),
        ),
    ]
