# Generated by Django 2.2.7 on 2019-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20191109_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancestor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ancestor',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
