# Generated by Django 2.2.7 on 2019-11-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20191109_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='mercator_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='mercator_y',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
